name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew jar
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
      with:
        name: UnitSpawn.jar
        path: build/libs/UnitSpawn.jar

    - name: Create Release
      if: strategy.job-index == 0
      id: create_release
      uses: actions/create-release@v1
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ github.run_number }}
          release_name: Release 1.0
          body: |
            UnitSpawn plugin Build ${{ github.run_number }}
          draft: false
          prerelease: false


    - name: Download ${{ matrix.assetName }}
      uses: actions/download-artifact@v2
      id: download
      with:
        name: ${{ matrix.assetName }}

    - name: Upload ${{ matrix.assetName }} to Release
      id: upload-desktop-asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ needs.gradleBuild.outputs.url }}
          asset_path: UnitSpawn.jar
          asset_name: ${{ matrix.assetName }}
          asset_content_type: application/zip
